web/router.ex
defmodule GrowJournal.Router do
  use GrowJournal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GrowJournal.Auth, repo: GrowJournal.Repo
  end

  pipeline :api do
    plug :accepts, ["json-api"]
    plug JaSerializer.ContentTypeNegotiation
    plug JaSerializer.Deserializer
  end

  scope "/", GrowJournal do
    pipe_through :browser

    get "/", PageController, :index
    get "/media/*filepath", MediaFilesController, :download

    resources "/users", UserController, only: [:new, :create]
    resources "/session", SessionController, except: [:update, :edit]

    resources "/plants", PlantController, only: [:index, :show]
  end

  scope "/admin", GrowJournal.Admin, as: :admin do
    pipe_through [:browser, :authenticate_user, :admin_user]

    resources "/users", UserController
    resources "/plants", PlantController do
      resources "/diseases", DiseaseController, except: [:index, :show]
      resources "/pests", PestController, except: [:index, :show]
      resources "/varieties", VarietyController, except: [:index, :show]
    end
  end

  scope "/", GrowJournal do
    pipe_through [:browser, :authenticate_user]

    get "/change_password", UserHomeController, :change_password
    post "/change_password", UserHomeController, :update_change_password
    put "/change_password", UserHomeController, :update_change_password

    get "/qrcodes", JournalController, :qrcodes
    resources "/journals", JournalController do
      resources "/entries", EntryController, except: [:index]
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", GrowJournal, as: :api do
    pipe_through :api

    resources "/plants", API.PlantController, only: [:index, :show] do
      resources "/diseases", API.DiseaseController, only: [:index, :show]
      resources "/pests", API.PestController, only: [:index, :show]
      resources "/varieties", API.VarietyController, only: [:index, :show]
    end
  end
end

web/views/layout_view.ex
defmodule GrowJournal.LayoutView do
  use GrowJournal.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello GrowJournal!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= journal_path(@conn, :index) %>">
            <img with="30" height="30" alt="GrowJournal Logo" src="<%= static_path(@conn, "/images/logo.svg") %>"/>
          </a>
          <ul class="nav navbar-nav">
            <li><%= link "Grow Journal", to: journal_path(@conn, :index) %></li>
            <li><%= link "Plants", to: plant_path(@conn, :index) %></li>
          </ul>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <%= if @current_user do %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                 role="button" aria-haspopup="true" aria-expanded="false">
                <%= @current_user.username %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <%= if @current_user.is_admin do %>
                <li><%= link "Admin area", to: admin_user_path(@conn, :index) %></li>
                <%= end %>
                <li><%= link "My dashboard", to: journal_path(@conn, :index) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link "Change my password", to: user_home_path(@conn, :change_password) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link "Logout", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
              </ul>
            </li>
          <%= else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Login", to: session_path(@conn, :new) %></li>
          <%= end %>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container-fluid -->
    <script src="//code.jquery.com/jquery-1.12.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous">
    </script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>