web/router.ex
defmodule GrowJournal.Router do
  use GrowJournal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GrowJournal.Auth, repo: GrowJournal.Repo
  end

  pipeline :api do
    plug :accepts, ["json-api"]
    plug JaSerializer.ContentTypeNegotiation
    plug JaSerializer.Deserializer
  end

  scope "/", GrowJournal do
    pipe_through :browser

    get "/", PageController, :index
    get "/media/*filepath", MediaFilesController, :download

    resources "/users", UserController, only: [:new, :create]
    resources "/session", SessionController, except: [:update, :edit]

    resources "/plants", PlantController, only: [:index, :show]
  end

  scope "/admin", GrowJournal.Admin, as: :admin do
    pipe_through [:browser, :authenticate_user, :admin_user]

    resources "/users", UserController
    resources "/plants", PlantController do
      resources "/diseases", DiseaseController, except: [:index, :show]
      resources "/pests", PestController, except: [:index, :show]
      resources "/varieties", VarietyController, except: [:index, :show]
    end
  end

  scope "/", GrowJournal do
    pipe_through [:browser, :authenticate_user]

    get "/change_password", UserHomeController, :change_password
    post "/change_password", UserHomeController, :update_change_password
    put "/change_password", UserHomeController, :update_change_password

    get "/qrcodes", JournalController, :qrcodes
    resources "/journals", JournalController do
      resources "/entries", EntryController, except: [:index]
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", GrowJournal, as: :api do
    pipe_through :api

    resources "/plants", API.PlantController, only: [:index, :show] do
      resources "/diseases", API.DiseaseController, only: [:index, :show]
      resources "/pests", API.PestController, only: [:index, :show]
      resources "/varieties", API.VarietyController, only: [:index, :show]
    end
  end
end

web/models/journal.ex
defmodule GrowJournal.Journal do
  use GrowJournal.Web, :model

  schema "journals" do
    belongs_to :user, GrowJournal.User
    belongs_to :plant, GrowJournal.Plant
    has_many :entries, GrowJournal.Entry
    field :qrcode_path, :string
    field :name, :string

    timestamps
  end

  @required_fields ~w()
  @optional_fields ~w(qrcode_path plant_id name)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def create_qrcode(user_id, journal_id, url) do
    qrcode = :qrcode.encode(url)
    png = :qrcode_demo.simple_png_encode(qrcode)
    short_path = "/#{user_id}/journals/#{journal_id}/qrcode.png"

    # folder to create if it doesn't exist
    folder_path = "#{System.cwd}/media/#{user_id}/journals/#{journal_id}/"
    full_path = "#{folder_path}/qrcode.png"
    :ok = :file.write_file(full_path, png)
    short_path
  end
end

web/controllers/journal_controller.ex
defmodule GrowJournal.JournalController do
  use GrowJournal.Web, :controller

  alias GrowJournal.Journal
  alias GrowJournal.Plant
  alias GrowJournal.Entry

  import Ecto.Model, only: [build: 2]

  plug :scrub_params, "journal" when action in [:create, :update]

  def action(conn, _) do
    apply(__MODULE__, action_name(conn), [conn, conn.params, conn.assigns.current_user])
  end

  defp build_plant_absolute_url(conn, journal_id) do
    port = ""
    if conn.port != 80 do
      port = ":#{conn.port}"
    end

    http = "http://"
    if conn.scheme != :http do
      http = "https://"
    end

    "#{http}#{conn.host}#{port}#{journal_path(conn, :show, journal_id)}"
  end

  def index(conn, _params, user) do
    entry_query = from entry in Entry, order_by: [desc: entry.when]

    journals = Repo.all from journal in user_journals(user),
               preload: [:plant, entries: ^entry_query]

    render(conn, "index.html", journals: journals)
  end

  def new(conn, _params, _user) do
    changeset = Journal.changeset(%Journal{})
    plants = Repo.all(Plant)
    render(conn, "new.html", changeset: changeset, plants: plants)
  end

  defp build_media_folder_structure_for_user(user, journal) do
    # folder to create if it doesn't exist
    folder_path = "#{System.cwd}/media/#{user.id}/journals/#{journal.id}/pictures"
    if not File.exists?(folder_path) do
      :ok = File.mkdir_p(folder_path)
    end
  end

  def create(conn, %{"journal" => journal_params}, user) do
    changeset = build(user, :journals)
    |> Journal.changeset(journal_params)

    case Repo.insert(changeset) do
      {:ok, journal} ->
        build_media_folder_structure_for_user(conn.assigns.current_user,
                                              journal)
        url = build_plant_absolute_url(conn, journal.id)
        qrcode = Journal.create_qrcode(conn.assigns.current_user.id,
                                       journal.id, url)
        journal = %Journal{journal| :qrcode_path => qrcode}
        Repo.update(journal)
        conn
        |> put_flash(:info, "Journal created successfully.")
        |> redirect(to: journal_path(conn, :index))
      {:error, changeset} ->
        plants = Repo.all(Plant)
        render(conn, "new.html", changeset: changeset, plants: plants)
    end
  end

  def show(conn, %{"id" => id}, user) do
    journal = Repo.get!(user_journals(user), id)
    |> Repo.preload(:plant)
    |> Repo.preload(:entries)
    render(conn, "show.html", journal: journal)
  end

  def edit(conn, %{"id" => id}, user) do
    journal = Repo.get!(user_journals(user), id)
    plants = Repo.all(Plant)
    changeset = Journal.changeset(journal)
    render(conn, "edit.html", journal: journal, changeset: changeset,
           plants: plants)
  end

  def update(conn, %{"id" => id, "journal" => journal_params}, user) do
    journal = Repo.get!(user_journals(user), id)
    changeset = Journal.changeset(journal, journal_params)

    case Repo.update(changeset) do
      {:ok, journal} ->
        conn
        |> put_flash(:info, "Journal updated successfully.")
        |> redirect(to: journal_path(conn, :show, journal))
      {:error, changeset} ->
        render(conn, "edit.html", journal: journal, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, user) do
    journal = Repo.get!(user_journals(user), id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(journal)

    conn
    |> put_flash(:info, "Journal deleted successfully.")
    |> redirect(to: journal_path(conn, :index))
  end

  def qrcodes(conn, _params, user) do
    journals = Repo.all(user_journals(user))
    |> Repo.preload(:plant)
    render(conn, "qrcodes.html", journals: journals)
  end

  def user_journals(user) do
    assoc(user, :journals)
  end
end

web/views/journal_view.ex
defmodule GrowJournal.JournalView do
  use GrowJournal.Web, :view

  def number_entries(journal) do
    Enum.count journal.entries
  end

  def last_picture([]) do
    nil
  end

  def last_picture([head|tail]) do
    cond do
      head.picture_path != nil ->
        head
      true ->
        last_picture(tail)
    end
  end
end

web/templates/journal/edit.html.eex
<h2>Edit Journal</h2>

<%= render "form.html", changeset: @changeset,
                        action: journal_path(@conn, :update, @journal),
                        back_path: journal_path(@conn, :index),
                        plants: @plants %>

web/templates/journal/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :plant_id, class: "control-label" %>
  <%= select f, :plant_id, Enum.map(@plants ++ [%{"name": "My plant is not listed", "id": nil}], fn p -> {p.name, p.id} end) %>
  <%= error_tag f, :plant_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
    <%= link "Back", to: @back_path, class: "btn btn-default" %>
  </div>
<% end %>

web/templates/journal/index.html.eex
<h2>My Journals</h2>

<%= for group_journal <- Enum.chunk(@journals, 3, 3, []) do %>
<div class="row">
  <%= for journal <- group_journal do %>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>
          <%= if journal.name do %>
          <%= link journal.name, to: journal_path(@conn, :show, journal) %>
          <%= else %>
            <%= link "This journal has no name", to: journal_path(@conn, :show, journal) %> <small><%= link "Edit", to: journal_path(@conn, :edit, journal) %></small>
          <%= end %>
          <%= link "x", to: journal_path(@conn, :delete, journal), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
        </h3>
        <div class="row">
          <div class="col-sm-4">
            <div class="row">
              <div class="col-xs-12">
                <%= if last_picture(journal.entries) do %>
                  <a href="/media/<%= last_picture(journal.entries).picture_path %>"><img src="/media/<%= last_picture(journal.entries).picture_path %>" class="img-rounded thumbnail" alt="<%= journal.plant.name %>"></a>
                <%= else %>
                  <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=No picture available&w=140&h=140" alt="No picture available" />
                <%= end %>
              </div>
            </div>
            <!-- <div class="row"> -->
            <!-- <div class="col-xs-12"> -->
            <!-- <ul class="list-unstyled"> -->
            <!-- <li><a href="#">See all pictures</a></li> -->
            <!-- </div> -->
          </div>
          <div class="col-sm-8">
            <h4>Last entries <small><%= link "Add new entry", to: journal_entry_path(@conn, :new, journal) %></small></h4>
            <ul>
              <%= for entry <- journal.entries do %>
              <li><%= entry.short_description %> <small><%= entry.when %></small></li>
              <%= end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= end %>
</div>
<%= end %>
<%= link "Add journal", to: journal_path(@conn, :new), class: "btn btn-primary" %>
<%= link "Print QR bar codes", to: journal_path(@conn, :qrcodes), class: "btn btn-default" %>

web/templates/journal/new.html.eex
<h2>Create new journal</h2>

<%= render "form.html", changeset: @changeset,
                        back_path: journal_path(@conn, :index),
                        action: journal_path(@conn, :create),
                        plants: @plants %>

web/templates/journal/qrcodes.html.eex
<!-- TODO: move this in sass -->
<style>
@media print {
  .navbar {
    display: none;
  }
  img {
    width: 100px;
    height: 100px;
  }
  a.btn {
    display: none;
  }
}
</style>
<h2>My qrcodes</h2>

<%= for group_journal <- Enum.chunk(@journals, 3, 3, []) do %>
<div class="row">
  <%= for journal <- group_journal do %>
  <div class="col-md-4 col-sm-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= journal.plant.name %></h3>
        <div class="row">
          <img src="/media/<%= journal.qrcode_path %>" alt="<%= journal.plant.name %> qr code">
          </div>
          <div class="row">
            Added on: <%= journal.inserted_at %>
          </div>
      </div>
    </div>
  </div>
  <%= end %>
</div>
<%= end %>
<%= link "Back", to: journal_path(@conn, :index), class: "btn btn-default" %>

web/templates/journal/show.html.eex
<h2>
  <%= if @journal.name do %>
    <%= @journal.name %>
  <% else %>
    This journal has no name
  <%= end %>
  <small>
    <%= link "Edit", to: journal_path(@conn, :edit, @journal) %>
  </small>
</h2>

<strong>QR Code:</strong>
<img src="/media<%= @journal.qrcode_path %>" />

<h3>Last entries</h3>
<table class="table table-hover">
  <thead>
    <th>Short description</th>
    <th>When</th>
    <th>Image</th>
    <th>Description</th>
    <th></th>
  </thead>
  <tbody>
    <%= for entry <- @journal.entries do %>
    <tr>
      <td><%= entry.short_description %></td>
      <td><%= entry.when %></td>
      <td>
        <%= if entry.picture_path do %>
        <a href="/media/<%= entry.picture_path %>"><img class="thumbnail img-thumbnail" src="/media/<%= entry.picture_path %>" alt="Entry picture" /></a>
        <%= end %>
    </td>
      <td><%= entry.long_description %></td>
      <td>
        <%= link "Edit", to: journal_entry_path(@conn, :edit, @journal, entry), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: journal_entry_path(@conn, :delete, @journal, entry), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
    </td>
    </tr>
    <%= end %>
  </tbody>
</table>
<%= link "Add new entry", to: journal_entry_path(@conn, :new, @journal), class: "btn btn-primary" %>
<%= link "Back", to: journal_path(@conn, :index), class: "btn btn-default" %>